// <auto-generated />
using System;
using BeehiveTycoon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeehiveTycoon.Migrations
{
    [DbContext(typeof(BeehiveTycoonContex))]
    [Migration("20220423164743_UlozeniHry")]
    partial class UlozeniHry
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BeehiveTycoon.Models.UlozenaHra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Postup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pozice")
                        .HasColumnType("int");

                    b.Property<int>("UzivatelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UzivatelId");

                    b.ToTable("UlozeneHry");
                });

            modelBuilder.Entity("BeehiveTycoon.Models.Uzivatel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Heslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uzivatele");
                });

            modelBuilder.Entity("BeehiveTycoon.Models.UlozenaHra", b =>
                {
                    b.HasOne("BeehiveTycoon.Models.Uzivatel", "Uzivatel")
                        .WithMany("UlozeneHry")
                        .HasForeignKey("UzivatelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzivatel");
                });

            modelBuilder.Entity("BeehiveTycoon.Models.Uzivatel", b =>
                {
                    b.Navigation("UlozeneHry");
                });
#pragma warning restore 612, 618
        }
    }
}
